<html>
<head>
<title>The Java Language Specification
 Exceptions</title>
</head>
<body BGCOLOR=#eeeeff text=#000000 LINK=#0000ff VLINK=#000077 ALINK=#ff0000>
 
<a href="index.html">Contents</a> | <a href="10.doc.html">Prev</a> | <a href="12.doc.html">Next</a> | <a href="j.index.doc1.html">Index</a>
<hr><br>
 
<a name="44043"></a>
<p><strong>
CHAPTER
 11 </strong></p>
<a name="44044"></a>
<h1>Exceptions</h1>
<hr><p>
<a name="44046"></a>
When a Java program violates the semantic constraints of the Java language, a 
Java Virtual Machine signals this error to the program as an <i>exception</i>. An example
of such a violation is an attempt to index outside the bounds of an array. Some 
programming languages and their implementations react to such errors by 
peremptorily terminating the program; other programming languages allow an 
implementation to react in an arbitrary or unpredictable way. Neither of these 
approaches is compatible with the design goals of Java: to provide portability and 
robustness. Instead, Java specifies that an exception will be thrown when semantic 
constraints are violated and will cause a non-local transfer of control from the 
point where the exception occurred to a point that can be specified by the programmer.
An exception is said to be <i>thrown</i> from the point where it occurred and 
is said to be <i>caught</i> at the point to which control is transferred.
<p><a name="44047"></a>
Java programs can also throw exceptions explicitly, using <code>throw</code> statements <a href="14.doc.html#237350">(&#167;14.16)</a>. This provides an alternative to the old-fashioned style of handling error conditions by returning funny values, such as the integer value <code>-1</code> where a negative value would not normally be expected. Experience shows that too often such funny values are ignored or not checked for by callers, leading to programs that are not robust, exhibit undesirable behavior, or both.<p>
<a name="44051"></a>
Every exception is represented by an instance of the class <code>Throwable</code> or one of its subclasses; such an object can be used to carry information from the point at which an exception occurs to the handler that catches it. Handlers are established by <code>catch</code> clauses of <code>try</code> statements <a href="14.doc.html#79311">(&#167;14.18)</a>. During the process of throwing an exception, a Java Virtual Machine abruptly completes, one by one, any expressions, statements, method and constructor invocations, static initializers, and field initialization expressions that have begun but not completed execution in the current thread. This process continues until a handler is found that indicates that it handles that particular exception by naming the class of the exception or a superclass of the class of the exception. If no such handler is found, then the method <code>uncaughtException</code> <a href="javalang.doc19.html#2901">(&#167;20.21.31)</a> is invoked for the <code>ThreadGroup</code> that is the parent of the current thread-thus every effort is made to avoid letting an exception go unhandled.<p>
<a name="44058"></a>
The Java exception mechanism is integrated with the Java synchronization model <a href="17.doc.html#26250">(&#167;17)</a>, so that locks are released as <code>synchronized</code> statements <a href="14.doc.html#79287">(&#167;14.17)</a> and invocations of <code>synchronized</code> methods (<a href="8.doc.html#55408">&#167;8.4.3.5</a>, <a href="15.doc.html#20448">&#167;15.11</a>) complete abruptly.<p>
<a name="44074"></a>
This chapter describes the different causes of exceptions <a href="11.doc.html#44088">(&#167;11.1)</a>. It details how exceptions are checked at compile time <a href="11.doc.html#44121">(&#167;11.2)</a> and processed at run time <a href="11.doc.html#44153">(&#167;11.3)</a>. A detailed example <a href="11.doc.html#44218">(&#167;11.4)</a> is then followed by an explanation of the exception hierarchy and the standard exception classes <a href="11.doc.html#44278">(&#167;11.5)</a>.<p>
<a name="44088"></a>
<h2>11.1    The Causes of Exceptions</h2>
<a name="44091"></a>
An exception is thrown for one of three <i>reasons</i>:
<p><ul><a name="44092"></a>
<li>An abnormal execution condition was synchronously detected by a Java Virtual Machine. Such conditions arise because:
<ul>
<a name="44093"></a>
<li>evaluation of an expression violates the normal semantics of the Java language, such as an integer divide by zero, as summarized in <a href="15.doc.html#79448">&#167;15.5</a>
<a name="44106"></a>
<li>an error occurs in loading or linking part of the Java program (<a href="12.doc.html#44459">&#167;12.2</a>, <a href="12.doc.html#44487">&#167;12.3</a>)
<a name="44107"></a>
<li>some limitation a resource is exceeded, such as using too much memory
</ul>
</ul><ul><a name="44108"></a>
<br><br>These exceptions are not thrown at an arbitrary point in the program, but rather at a point where they are specified as a possible result of an expression evaluation or statement execution.
</ul><ul><a name="44112"></a>
<li>A <code>throw</code> statement <a href="14.doc.html#237350">(&#167;14.16)</a> was executed in Java code.
<a name="44113"></a>
<li>An asynchronous exception occurred either because:
<ul>
<a name="44114"></a>
<li>the method <code>stop</code> of class <code>Thread</code> <a href="javalang.doc18.html#8096">(&#167;20.20.16)</a> was invoked
<a name="44118"></a>
<li>an internal error has occurred in the virtual machine <a href="11.doc.html#44395">(&#167;11.5.2.2)</a>
</ul>
</ul><a name="44119"></a>
Exceptions are represented by instances of the class <code>Throwable</code> and instances of its subclasses. These classes are, collectively, the <i>exception classes</i>.<p>
<a name="44121"></a>
<h2>11.2    Compile-Time Checking of Exceptions</h2>
<a name="44122"></a>
The Java language checks, at compile time, that a Java program contains handlers 
for <i>checked exceptions</i>, by analyzing which checked exceptions can result from 
execution of a method or constructor. For each checked exception which is a possible
result, the <code>throws</code> clause for the method <a href="8.doc.html#78323">(&#167;8.4.4)</a> or constructor <a href="8.doc.html#244611">(&#167;8.6.4)</a> 
must mention the class of that exception or one of the superclasses of the class of 
that exception. This compile-time checking for the presence of exception handlers 
is designed to reduce the number of exceptions which are not properly handled.
<p><a name="44129"></a>
The <i>unchecked exceptions classes</i> are the class <code>RuntimeException</code> and its subclasses, and the class <code>Error</code> and its subclasses. All other exception classes are <i>checked exception classes</i>. The standard Java API defines a number of exception classes, both checked and unchecked. Additional exception classes, both checked and unchecked, may be declared by Java programmers. See <a href="11.doc.html#44278">&#167;11.5</a> for a description of the Java exception class hierarchy and the exception classes defined by the standard Java API and Java Virtual Machine.<p>
<a name="44133"></a>
The checked exception classes named in the <code>throws</code> clause are part of the contract between the implementor and user of the method or constructor. The <code>throws</code> clause of an overriding method may not specify that this method will result in throwing any checked exception which the overridden method is not permitted, by its <code>throws</code> clause, to throw. When interfaces are involved, more than one method declaration may be overridden by a single overriding declaration. In this case, the overriding declaration must have a <code>throws</code> clause that is compatible with <i>all</i> the overridden declarations <a href="9.doc.html#78651">(&#167;9.4)</a>.<p>
<a name="44146"></a>
Variable initializers for fields <a href="8.doc.html#24510">(&#167;8.3.2)</a> and static initializers <a href="8.doc.html#39245">(&#167;8.5)</a> must not result in a checked exception; if one does, a compile-time error occurs.<p>
<a name="44147"></a>
<h3>11.2.1    Why Errors are Not Checked</h3>
<a name="44148"></a>
Those unchecked exception classes which are the <i>error classes</i> (<code>Error</code> and its 
subclasses) are exempted from compile-time checking because they can occur at 
many points in the program and recovery from them is difficult or impossible. A 
Java program declaring such exceptions would be cluttered, pointlessly.
<p><a name="44149"></a>
<h3>11.2.2    Why Runtime Exceptions are Not Checked</h3>
<a name="44150"></a>
The <i>runtime exception classes</i> (<code>RuntimeException</code> and its subclasses) are 
exempted from compile-time checking because, in the judgment of the designers 
of Java, having to declare such exceptions would not aid significantly in establishing
the correctness of Java programs. Many of the operations and constructs of the 
Java language can result in runtime exceptions. The information available to a 
Java compiler, and the level of analysis the compiler performs, are usually not sufficient
to establish that such runtime exceptions cannot occur, even though this 
may be obvious to the Java programmer. Requiring such exception classes to be 
declared would simply be an irritation to Java programmers.
<p><a name="44151"></a>
For example, certain code might implement a circular data structure that, by construction, can never involve <code>null</code> references; the programmer can then be certain &#32;that a <code>NullPointerException</code> cannot occur, but it would be difficult for a compiler to prove it. The theorem-proving technology that is needed to establish such global properties of data structures is beyond the scope of this Java Language Specification.<p>
<a name="44153"></a>
<h2>11.3    Handling of an Exception</h2>
<a name="44154"></a>
When an exception is thrown, control is transferred from the code that caused the 
exception to the nearest dynamically-enclosing <code>catch</code> clause of a <code>try</code> statement 
<a href="14.doc.html#79311">(&#167;14.18)</a> that handles the exception.
<p><a name="44158"></a>
A statement or expression is <i>dynamically enclosed</i> by a <code>catch</code> clause if it appears within the <code>try</code> block of the <code>try</code> statement of which the <code>catch</code> clause is a part, or if the caller of the statement or expression is dynamically enclosed by the <code>catch</code> clause.<p>
<a name="44159"></a>
The <i>caller</i> of a statement or expression depends on where it occurs:<p>
<ul><a name="44160"></a>
<li>If within a method, then the caller is the method invocation expression <a href="15.doc.html#20448">(&#167;15.11)</a> that was executed to cause the method to be invoked.
<a name="44164"></a>
<li>If within a constructor or the initializer for an instance variable, then the caller is the class instance creation expression <a href="15.doc.html#41147">(&#167;15.8)</a> or the method invocation of <code>newInstance</code> that was executed to cause an object to be created.
<a name="44168"></a>
<li>If within a static initializer or an initializer for a <code>static</code> variable, then the caller is the expression that used the class or interface so as to cause it to be initialized.
</ul><a name="44169"></a>
Whether a particular <code>catch</code> clause <i>handles</i> an exception is determined by comparing the class of the object that was thrown to the declared type of the parameter of the <code>catch</code> clause. The <code>catch</code> clause handles the exception if the type of its parameter is the class of the exception or a superclass of the class of the exception. Equivalently, a <code>catch</code> clause will catch any exception object that is an <code>instanceof</code> <a href="15.doc.html#80289">(&#167;15.19.2)</a> the declared parameter type.<p>
<a name="44173"></a>
The control transfer that occurs when an exception is thrown causes abrupt completion of expressions <a href="15.doc.html#79448">(&#167;15.5)</a> and statements <a href="14.doc.html#5894">(&#167;14.1)</a> until a <code>catch</code> clause is encountered that can handle the exception; execution then continues by executing the block of that <code>catch</code> clause. The code that caused the exception is never resumed.<p>
<a name="44180"></a>
If no <code>catch</code> clause handling an exception can be found, then the current thread (the thread that encountered the exception) is terminated, but only after all <code>finally</code> clauses have been executed and the method <code>uncaughtException</code> <a href="javalang.doc19.html#2901">(&#167;20.21.31)</a> has been invoked for the <code>ThreadGroup</code> that is the parent of the current thread.<p>
<a name="44184"></a>
In situations where it is desirable to ensure that one block of code is always executed after another, even if that other block of code completes abruptly, a <code>try</code> statement with a <code>finally</code> clause <a href="14.doc.html#236653">(&#167;14.18.2)</a> may be used. If a <code>try</code> or <code>catch</code> block in a <code>try</code>-<code>finally</code> or <code>try</code>-<code>catch</code>-<code>finally</code> statement completes abruptly, then the <code>finally</code> clause is executed during propagation of the exception, even if no matching <code>catch</code> clause is ultimately found. If a <code>finally</code> clause is executed because of abrupt completion of a <code>try</code> block and the <code>finally</code> clause itself completes abruptly, then the reason for the abrupt completion of the <code>try</code> block is discarded and the new reason for abrupt completion is propagated from there.<p>
<a name="44188"></a>
The exact rules for abrupt completion and for the catching of exceptions are specified in detail with the specification of each statement in <a href="14.doc.html#44383">&#167;14</a> and for expressions in <a href="15.doc.html#4709">&#167;15</a> (especially <a href="15.doc.html#79448">&#167;15.5</a>).<p>
<a name="44199"></a>
<h3>11.3.1    Exceptions are Precise</h3>
<a name="44200"></a>
Exceptions in Java are <i>precise</i>: when the transfer of control takes place, all effects 
of the statements executed and expressions evaluated before the point from which 
the exception is thrown must appear to have taken place. No expressions, statements,
or parts thereof that occur after the point from which the exception is 
thrown may appear to have been evaluated. If optimized code has speculatively 
executed some of the expressions or statements which follow the point at which 
the exception occurs, such code must be prepared to hide this speculative execution
from the user-visible state of the Java program.
<p><a name="44202"></a>
<h3>11.3.2    Handling Asynchronous Exceptions</h3>
<a name="44203"></a>
Most exceptions in Java occur synchronously as a result of an action by the thread 
in which they occur, and at a point in the Java program that is specified to possibly 
result in such an exception. An asynchronous exception is, by contrast, an exception
that can potentially occur at any point in the execution of a Java program.
<p><a name="47137"></a>
Asynchronous exceptions are rare in Java. They occur only as a result of:<p>
<ul><a name="44205"></a>
<li>An invocation of the <code>stop</code> methods of class <code>Thread</code> (<a href="javalang.doc18.html#8095">&#167;20.20.15</a>, <a href="javalang.doc18.html#8096">&#167;20.20.16</a>) or <code>ThreadGroup</code> (<a href="javalang.doc19.html#2885">&#167;20.21.8</a>, <a href="javalang.doc19.html#2886">&#167;20.21.9</a>)
<a name="44209"></a>
<li>An <code>InternalError</code> <a href="11.doc.html#44395">(&#167;11.5.2.2)</a> in the Java Virtual Machine
</ul><a name="44210"></a>
The <code>stop</code> methods may be invoked by one thread to affect another thread or all the 
threads in a specified thread group. They are asynchronous because they may 
occur at any point in the execution of the other thread or threads. An 
<code>InternalError</code> &#32;is considered asynchronous so that it may be handled using the 
same mechanism that handles the <code>stop</code> method, as will now be described.
<p><a name="44211"></a>
Java permits a small but bounded amount of execution to occur before an asynchronous exception is thrown. This delay is permitted to allow optimized code to detect and throw these exceptions at points where it is practical to handle them while obeying the semantics of the Java language.<p>
<a name="44212"></a>
A simple implementation might poll for asynchronous exceptions at the point of each control transfer instruction. Since a Java program has a finite size, this provides a bound on the total delay in detecting an asynchronous exception. Since no asynchronous exception will occur between control transfers, the code generator has some flexibility to reorder computation between control transfers for greater performance.<p>
<a name="46637"></a>
The paper <i>Polling Efficiently on Stock Hardware </i>by Mark Feeley, <i>Proc. 1993 Conference on Functional Programming and Computer Architecture</i>, Copenhagen, Denmark, pp. 179-187, is recommended as further reading.<p>
<a name="44216"></a>
Like all exceptions, asynchronous exceptions are precise <a href="11.doc.html#44199">(&#167;11.3.1)</a>.<p>
<a name="44218"></a>
<h2>11.4    An Example of Exceptions</h2>
<a name="44219"></a>
Consider the following example:
<p><pre><a name="46616"></a>
class TestException extends Exception {
<br><a name="46618"></a>	TestException() { super(); }
<br><br><a name="44223"></a>	TestException(String s) { super(s); }
<br><a name="44224"></a>}
<a name="46659"></a>
class Test {
<a name="44226"></a>
	public static void main(String[] args) {
<a name="44227"></a>		for (int i = 0; i &lt; args.length; i++) {
</pre><pre><a name="46972"></a>
			try {
<a name="44229"></a>				thrower(args[i]);
<a name="44230"></a>				System.out.println("Test \"" + args[i] +
<a name="44231"></a>					"\" didn't throw an exception");
<a name="44232"></a>			} catch (Exception e) {
<a name="44233"></a>				System.out.println("Test \"" + args[i] +
<a name="44234"></a>					"\" threw a " + e.getClass() +
<a name="44235"></a>					"\n &#32; &#32; &#32; &#32;with message: " + e.getMessage());
<a name="44236"></a>			}
<a name="44237"></a>		}
<a name="44238"></a>	}
<br><a name="44239"></a>
	static int thrower(String s) throws TestException {
<a name="44240"></a>		try {
<a name="44241"></a>			if (s.equals("divide")) {
<a name="44242"></a>				int i = 0;
<a name="44243"></a>				return i/i;
<a name="44244"></a>			}
<a name="44245"></a>			if (s.equals("null")) {
<a name="44246"></a>				s = null;
<a name="44247"></a>				return s.length();
<a name="44248"></a>			}
<a name="44249"></a>			if (s.equals("test"))
<a name="44250"></a>				throw new TestException("Test message");
<a name="44251"></a>			return 0;
<a name="44252"></a>		} finally {
<a name="44253"></a>			System.out.println("[thrower(\"" + s +
<a name="46660"></a>					"\") done]");
<a name="44254"></a>		}
<a name="44255"></a>	}
<a name="44256"></a>}
</pre><a name="44257"></a>
If we execute the test program, passing it the arguments:
<p><pre><a name="44258"></a>divide null not test
</pre><a name="44259"></a>
it produces the output:
<p><pre><a name="44260"></a>
[thrower("divide") done]
<a name="44261"></a>Test "divide" threw a class java.lang.ArithmeticException
<a name="44262"></a> &#32; &#32; &#32; &#32;with message: / by zero
<a name="44263"></a>[thrower("null") done]
<a name="44264"></a>Test "null" threw a class java.lang.NullPointerException
<a name="44265"></a> &#32; &#32; &#32; &#32;with message: null
<a name="44266"></a>[thrower("not") done]
<a name="44267"></a>Test "not" didn't throw an exception
<a name="44268"></a>[thrower("test") done]
<a name="44269"></a>Test "test" threw a class TestException
<a name="44270"></a> &#32; &#32; &#32; &#32;with message: Test message
</pre><a name="44271"></a>
This example declares an exception class <code>TestException</code>. The <code>main</code> method of class <code>Test</code> invokes the <code>thrower</code> method four times, causing exceptions to be thrown three of the four times. The <code>try</code> statement in method <code>main</code> catches each exception that the <code>thrower</code> throws. Whether the invocation of <code>thrower</code> completes normally or abruptly, a message is printed describing what happened.<p>
<a name="44272"></a>
The declaration of the method <code>thrower</code> must have a <code>throws</code> clause because it &#32;can throw instances of <code>TestException</code>, which is a checked exception class <a href="11.doc.html#44121">(&#167;11.2)</a>. A compile-time error would occur if the <code>throws</code> clause were omitted.<p>
<a name="44276"></a>
Notice that the <code>finally</code> clause is executed on every invocation of <code>thrower</code>, whether or not an exception occurs, as shown by the "<code>[thrower(</code>...<code>)&#32;done]</code>" output that occurs for each invocation<p>
<a name="44278"></a>
<h2>11.5    The Exception Hierarchy</h2>
<a name="44279"></a>
The possible exceptions in a Java program are organized in a hierarchy of classes, 
rooted at class <code>Throwable</code> (<a href="11.doc.html#44278">&#167;11.5</a>, <a href="javalang.doc20.html#46198">&#167;20.22</a>), a direct subclass of <code>Object</code>. The 
classes <code>Exception</code> and <code>Error</code> are direct subclasses of <code>Throwable</code>. The class 
<code>RuntimeException</code> is a direct subclass of <code>Exception</code>.
<p><a name="55113"></a>
The exception classes declared by the standard packages <code>java.lang</code>, <code>java.util</code>, <code>java.io</code> and <code>java.net</code> are called the <i>standard exception classes</i>.<p>
<a name="55114"></a>
Java programs can use the pre-existing exception classes in <code>throw</code> statements, or define additional exception classes, as subclasses of <code>Throwable</code> or of any of its subclasses, as appropriate. To take advantage of Java's compile-time checking for exception handlers, it is typical to define most new exception classes as checked exception classes, specifically as subclasses of <code>Exception</code> that are not subclasses of <code>RuntimeException</code>.<p>
<a name="44285"></a>
<h3>11.5.1    The Classes <code>Exception</code> and <code>RuntimeException</code></h3>
<a name="44286"></a>
The class <code>Exception</code> is the superclass of all the exceptions that ordinary programs
may wish to recover from.
<p><a name="44287"></a>
<h4>11.5.1.1    Standard Runtime Exceptions</h4>
<a name="44288"></a>
The class <code>RuntimeException</code> is a subclass of class <code>Exception</code>. The subclasses 
of <code>RuntimeException</code> are unchecked exception classes.
<p><a name="44289"></a>
Package <code>java.lang</code> defines the following standard unchecked runtime exceptions, which, like all other classes in package <code>java.lang</code>, are implicitly imported and therefore may be referred to by their simple names:<p>
<ul><a name="44290"></a>
<li><code>ArithmeticException</code>: An exceptional arithmetic situation has arisen, such as an integer division <a href="15.doc.html#5047">(&#167;15.16.2)</a> operation with a zero divisor. 
<a name="44297"></a>
<li><code>ArrayStoreException</code>: An attempt has been made to store into an array component a value whose class is not assignment compatible with the component type of the array (<a href="10.doc.html#11430">&#167;10.10</a>, <a href="15.doc.html#5295">&#167;15.25.1</a>).
<a name="44304"></a>
<li><code>ClassCastException</code>: An attempt has been made to cast (<a href="5.doc.html#176921">&#167;5.4</a>, <a href="15.doc.html#238146">&#167;15.15</a>) a reference to an object to an inappropriate type.
<a name="44305"></a>
<li><code>IllegalArgumentException</code>: A method was passed an invalid or inappropriate argument or invoked on an inappropriate object. Subclasses of this class include:
<ul>
<a name="49959"></a>
<li><code>IllegalThreadStateException:</code> A thread was not in an appropriate state for a requested operation.
<a name="49960"></a>
<li><code>NumberFormatException</code>: An attempt was made to convert a <code>String</code> to a value of a numeric type, but the <code>String</code> did not have an appropriate format.
</ul>
<a name="44308"></a>
<li><code>IllegalMonitorStateException</code>: A thread has attempted to wait on (<a href="javalang.doc1.html#33394">&#167;20.1.6</a>, <a href="javalang.doc1.html#14926">&#167;20.1.7</a>, <a href="javalang.doc1.html#32520">&#167;20.1.8</a>) or notify (<a href="javalang.doc1.html#13789">&#167;20.1.9</a>, <a href="javalang.doc1.html#13790">&#167;20.1.10</a>) other threads waiting on an object that it has not locked.
<a name="44315"></a>
<li><code>IndexOutOfBoundsException</code>: Either an index of some sort (such as to an array, a string, or a vector) or a subrange, specified either by two index values or by an index and a length, was out of range.
<a name="44316"></a>
<li><code>NegativeArraySizeException</code>: An attempt was made to create an array with a negative length <a href="15.doc.html#46168">(&#167;15.9)</a>.
<a name="44320"></a>
<li><code>NullPointerException</code>: An attempt was made to use a null reference in a case where an object reference was required.
<a name="44324"></a>
<li><code>SecurityException</code>: A security violation was detected <a href="javalang.doc16.html#46274">(&#167;20.17)</a>.
</ul><a name="44325"></a>
Package <code>java.util</code> defines the following additional standard unchecked runtime 
exceptions:
<p><ul><a name="44326"></a>
<li><code>java.util.EmptyStackException</code>: An attempt was made to access an element of an empty stack.
<a name="44327"></a>
<li><code>java.util.NoSuchElementException</code>: An attempt was made to access an element of an empty vector.
</ul><a name="44328"></a>
<h4>11.5.1.2    Standard Checked Exceptions</h4>
<a name="44329"></a>
The standard subclasses of <code>Exception</code> other than <code>RuntimeException</code> are all 
checked exception classes.
<p><a name="44330"></a>
Package <code>java.lang</code> defines the following standard exceptions, which, like all other classes in package <code>java.lang</code>, are implicitly imported and therefore may be referred to by their simple names:<p>
<ul><a name="44331"></a>
<li><code>ClassNotFoundException</code>: A class or interface with a specified name could not be found <a href="javalang.doc2.html#28532">(&#167;20.3.8)</a>.
<a name="44338"></a>
<li><code>CloneNotSupportedException</code>: The <code>clone</code> method <a href="javalang.doc1.html#14934">(&#167;20.1.5)</a> of class <code>Object</code> &#32;has been invoked to clone an object, but the class of that object does not implement the <code>Cloneable</code> interface.
<a name="44339"></a>
<li><code>IllegalAccessException</code>: An attempt has been made to load a class using a string giving its fully qualified name, but the currently executing method does not have access to the definition of the specified class because the class is not <code>public</code> and is in another package.
<a name="44340"></a>
<li><code>InstantiationException</code>: An attempt was made to create an instance of a class using the <code>newInstance</code> method in class <code>Class</code>, but the specified class object cannot be instantiated because it is an interface, is <code>abstract</code>, or is an array.
<a name="44341"></a>
<li><code>InterruptedException</code>: The current thread was waiting, and another thread has interrupted the current thread, using the <code>interrupt</code> method of class <code>Thread</code> <a href="javalang.doc18.html#29179">(&#167;20.20.31)</a>.
</ul><a name="44345"></a>
Package <code>java.io</code> defines the following additional standard exceptions:
<p><ul><a name="44346"></a>
<li><code>java.io.IOException</code>: A requested I/O operation could not be completed normally. Subclasses of this class include:
<ul>
<a name="44347"></a>
<li><code>java.io.EOFException</code>: End of file has been encountered before normal completion of an input operation.
<a name="44348"></a>
<li><code>java.io.FileNotFoundException</code>: A file with the name specified by a file name string or path was not found within the file system.
<a name="44349"></a>
<li><code>java.io.InterruptedIOException</code>: The current thread was waiting for completion of an I/O operation, and another thread has interrupted the current thread, using the <code>interrupt</code> method of class <code>Thread</code> <a href="javalang.doc18.html#29179">(&#167;20.20.31)</a>.
<a name="44353"></a>
<li><code>java.io.UTFDataFormatException</code>: A requested conversion of a string to or from Java modified UTF-8 format could not be completed (<a href="javaio.doc.html#28916">&#167;22.1.15</a>, <a href="javaio.doc.html#29074">&#167;22.2.14</a>) because the string was too long or because the purported UTF-8 data was not the result of encoding a Unicode string into UTF-8.
</ul>
</ul><a name="44360"></a>
The standard package <code>java.net</code> defines the following additional subclasses of 
<code>java.io.IOException</code>:
<p><a name="44361"></a>
u	 <code>java.net.MalformedURLException</code>: A string that was provided as a URL, or as part of a URL, had an inappropriate format or specified an unknown protocol.<p>
<ul><ul>
<a name="44362"></a>
<li><code>java.net.ProtocolException</code>: Some aspect of a network protocol was not correctly carried out.
<a name="44363"></a>
<li><code>java.net.SocketException</code>: An operation involving a socket could not be completed normally.
<a name="44364"></a>
<li><code>java.net.UnknownHostException</code>: The name of a network host could not be resolved to a network address.
<a name="44365"></a>
<li><code>java.net.UnknownServiceException</code>: The network connection cannot support the requested service.
</ul>
</ul><a name="44367"></a>
<h3>11.5.2    The Class <code>Error</code></h3>
<a name="44368"></a>
The class <code>Error</code> and its standard subclasses are exceptions from which ordinary 
programs are not ordinarily expected to recover. The class <code>Error</code> is a separate 
subclass of <code>Throwable</code>, distinct from <code>Exception</code> in the class hierarchy, to allow 
programs to use the idiom:
<p><pre><a name="44369"></a>} catch (Exception e) {
</pre><a name="44370"></a>
to catch all exceptions from which recovery may be possible without catching 
errors from which recovery is typically not possible.
<p><a name="44371"></a>
Package <code>java.lang</code> defines all the error classes described here. These classes, like all other classes in package <code>java.lang</code>, are implicitly imported and therefore may be referred to by their simple names.<p>
<a name="44372"></a>
<h4>11.5.2.1    Loading and Linkage Errors</h4>
<a name="44373"></a>
A Java Virtual Machine throws an object that is an instance of a subclass of 
<code>LinkageError</code> &#32;when a loading, linkage, preparation, verification or initialization 
error occurs:
<p><ul><a name="44377"></a>
<li>The loading process is described in <a href="12.doc.html#44459">&#167;12.2</a>. The errors <code>ClassFormatError</code>, <code>ClassCircularityError</code>, and <code>NoClassDefFoundError</code> are described there.
<a name="47893"></a>
<li>The linking process is described in <a href="12.doc.html#44487">&#167;12.3</a>. The linking errors are described there. These errors include <code>IllegalAccessError</code>,<code> InstantiationError</code>, <code>NoSuchFieldError</code>, and <code>NoSuchMethodError</code>, all of which are subclasses of <code>IncompatibleClassChangeError</code>, and, also, <code>UnsatisfiedLinkError</code>.
<a name="47897"></a>
<li>The class verification process is described in <a href="12.doc.html#44491">&#167;12.3.1</a>. The verification failure error <code>VerifyError</code> is described there.
<a name="44389"></a>
<li>The class preparation process is described in <a href="12.doc.html#47979">&#167;12.3.2</a>. The preparation error described there is <code>AbstractMethodError</code>.
<a name="44393"></a>
<li>The class initialization process is described in <a href="12.doc.html#44557">&#167;12.4</a>. A virtual machine will throw the error <code>ExceptionInInitializerError</code> if execution of a static initializer or of an initializer for a <code>static</code> field results in an exception that is not an <code>Error</code> or a subclass of <code>Error</code>.
</ul><a name="44395"></a>
<h4>11.5.2.2    Virtual Machine Errors</h4>
<a name="44396"></a>
A Java Virtual Machine throws an object that is an instance of a subclass of the 
class <code>VirtualMachineError</code> when an internal error or resource limitation prevents
it from implementing the semantics of the Java Language. This language 
specification and the Java Virtual Machine Specification define the following virtual
machine errors:
<p><ul><a name="44397"></a>
<li><code>InternalError</code>: An internal error has occurred in a Java Virtual Machine, because of a fault in the software implementing the virtual machine, a fault in the underlying host system software, or a fault in the hardware. This error is delivered asynchronously when it is detected, and may occur at any point in a Java program.
<a name="44398"></a>
<li><code>OutOfMemoryError</code>: A Java Virtual Machine has run out of either virtual or physical memory, and the automatic storage manager wasn't able to reclaim enough memory to satisfy an object creation request.
<a name="44399"></a>
<li><code>StackOverflowError</code>: A Java Virtual Machine has run out of stack space for a thread, typically because the thread is doing an unbounded number of recursive invocations due to a fault in the executing program.
<a name="44400"></a>
<li><code>UnknownError</code>: An exception or error has occurred but, for some reason, a Java Virtual Machine is unable to report the actual exception or error.
</ul><a name="44401"></a>
A sophisticated Java program may be designed to handle <code>OutOfMemoryError</code> and 
attempt to recover from it, perhaps by carefully dropping references to objects.
<p><a name="47538"></a>
We are exploring enhancements to Java to simplify handling of out-of-memory conditions. One possibility would be to support automatic suspension of a thread which encounters an <code>OutOfMemoryError</code> and allow another thread to handle the <code>error</code> situation. Such a technique might also permit a Java program to recover from a <code>StackOverflowError</code> if this overflow does not result from a nonterminating recursion. Suggestions for other approaches are welcomed.<p>
<a name="55170"></a>
<p>


<hr>
<!-- This inserts footnotes--><p>
<a href="index.html">Contents</a> | <a href="10.doc.html">Prev</a> | <a href="12.doc.html">Next</a> | <a href="j.index.doc1.html">Index</a>
<p>
<font size=-1>Java Language Specification (HTML generated by Suzette Pelouch on February 24, 1998)<br>
<i><a href="jcopyright.doc.html">Copyright &#169 1996 Sun Microsystems, Inc.</a>
All rights reserved</i>
<br>
Please send any comments or corrections to <a href="mailto:doug.kramer@sun.com">doug.kramer@sun.com</a>
</font>
</body></html>